version: '3.8'  # pode remover essa linha se quiser
services:
  mysql:
    image: mysql:8
    container_name: crud-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
